### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mideoye** [QualiSystems/Spirent-TestCenter-Chassis-Shell-2G#1]
Hi, Please can you update the broken link in readme.md:

Device Name Attributes: https://github.com/QualiSystems/Spirent-TestCenterChassis-Shell-2G/blob/master/*device-name-attributes

**Comment by Costya-Y** [comment]
Hi @mideoye 

Thank you for reporting it, we will take a look at it

**Comment by cr-yoramshamir** [comment]
Fixed.

**Comment by mideoye** [comment]
Thanks
